stages:
  - build
build:
  stage: build
  tags:
    - tg-shell
  image:
    name: python:3.12
    entrypoint: [""]
  script:
    - if (!(Test-Path "/kaniko/.docker" -PathType Container)) { mkdir "/kaniko/.docker" }
    - $auth = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("json_key:${CI_REGISTRY_KEY}"))
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$auth\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --force
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_SHORT_SHA}"
      
